In [7]:
# import python libraries

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt # visualizing data
%matplotlib inline
import seaborn as sns
import ast

In [8]:
# import csv file
df = pd.read_csv(r'/Users/noja/Downloads/IMBD 2.csv')

In [9]:
df.shape

(129891, 9)

In [10]:
df.head(20)

,movie,genre,runtime,certificate,rating,stars,description,votes,director
0,The Witcher,"Action, Adventure, Drama",60 min,A,8.1,"['Henry Cavill, ', 'Freya Allan, ', 'Anya Chal...","Geralt of Rivia, a solitary monster hunter, st...","5,39,085",NaN
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163 min,UA,8.0,"['Tom Cruise, ', 'Hayley Atwell, ', 'Ving Rham...",Ethan Hunt and his IMF team must track down a ...,"1,06,759",['Christopher McQuarrie']
2,Sound of Freedom,"Action, Biography, Drama",131 min,PG-13,7.9,"['Jim Caviezel, ', 'Mira Sorvino, ', 'Bill Cam...",The incredible true story of a former governme...,"41,808",['Alejandro Monteverde']
3,Secret Invasion,"Action, Adventure, Drama",47 min,UA 16+,6.2,"['Samuel L. Jackson, ', 'Emilia Clarke, ', 'Do...",Fury and Talos try to stop the Skrulls who hav...,"40,536",NaN
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,NaN,7.5,"['Zoe Saldana, ', 'Laysla De Oliveira, ', 'Dav...",Joe attempts to balance her personal and profe...,"3,203",NaN
5,They Cloned Tyrone,"Action, Comedy, Mystery",122 min,R,6.7,"['John Boyega, ', 'Jamie Foxx, ', 'Teyonah Par...",A series of eerie events thrusts an unlikely t...,"14,271",['Juel Taylor']
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52 min,Not Rated,8.3,"['Anson Mount, ', 'Ethan Peck, ', 'Christina C...","A prequel to Star Trek: The Original Series, t...","45,723",NaN
7,One Piece,"Action, Adventure, Comedy",NaN,NaN,NaN,"['IÃ±aki Godoy, ', 'Mackenyu, ', 'Emily Rudd, '...","In a seafaring world, a young pirate captain s...",NaN,NaN
8,Twisted Metal,"Action, Adventure, Comedy",30 min,NaN,7.5,"['Anthony Mackie, ', 'Tahj Vaughans, ', 'Steph...",Follows a motor-mouthed outsider offered a cha...,"4,334",NaN
9,The Flash,"Action, Adventure, Fantasy",144 min,UA,6.9,"['Ezra Miller, ', 'Michael Keaton, ', 'Sasha C...",Barry Allen uses his super speed to change the...,"1,26,445",['Andy Muschietti']
10,Jack Ryan,"Action, Drama, Thriller",60 min,16+,8.0,"['John Krasinski, ', 'Wendell Pierce, ', 'Mich...","Up-and-coming CIA analyst, Jack Ryan, is thrus...","1,60,501",NaN
11,Transformers: Rise of the Beasts,"Action, Adventure, Sci-Fi",127 min,UA,6.1,"['Anthony Ramos, ', 'Dominique Fishback, ', 'L...","During the '90s, a new faction of Transformers...","62,180",['Steven Caple Jr.']
12,Game of Thrones,"Action, Adventure, Drama",57 min,A,9.2,"['Emilia Clarke, ', 'Peter Dinklage, ', 'Kit H...",Nine noble families fight for control over the...,"21,86,960",NaN
13,Indiana Jones and the Dial of Destiny,"Action, Adventure",154 min,UA,6.8,"['Harrison Ford, ', 'Phoebe Waller-Bridge, ', ...",Archaeologist Indiana Jones races against time...,"87,700",['James Mangold']
14,Invincible,"Animation, Action, Adventure",50 min,18,8.7,"['Steven Yeun, ', 'J.K. Simmons, ', 'Sandra Oh...",An adult animated series based on the Skybound...,"1,59,339",NaN
15,The Boys,"Action, Comedy, Crime",60 min,18+,8.7,"['Karl Urban, ', 'Jack Quaid, ', 'Antony Starr...",A group of vigilantes set out to take down cor...,"5,70,614",NaN
16,The Out-Laws,"Action, Comedy, Crime",95 min,A,5.4,"['Adam Devine, ', 'Pierce Brosnan, ', 'Ellen B...",A straight-laced bank manager about to marry t...,"24,122",['Tyler Spindel']
17,Justified,"Action, Crime, Drama",44 min,NaN,8.6,"['Timothy Olyphant, ', 'Nick Searcy, ', 'Joell...","Enforcing his own brand of justice, U.S. Marsh...","1,09,050",NaN
18,Guardians of the Galaxy Vol. 3,"Action, Adventure, Comedy",150 min,UA,8.1,"['Chris Pratt, ', 'Chukwudi Iwuji, ', 'Bradley...","Still reeling from the loss of Gamora, Peter Q...","2,37,866",['James Gunn']
19,Spider-Man: Across the Spider-Verse,"Animation, Action, Adventure",140 min,U,8.9,"['Shameik Moore, ', 'Hailee Steinfeld, ', 'Bri...","Miles Morales catapults across the Multiverse,...","1,96,674",NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129891 entries, 0 to 129890
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   movie        129891 non-null  object
 1   genre        129891 non-null  object
 2   runtime      109005 non-null  object
 3   certificate  23850 non-null   object
 4   rating       114381 non-null  float64
 5   stars        124676 non-null  object
 6   description  129891 non-null  object
 7   votes        114393 non-null  object
 8   director     88611 non-null   object
dtypes: float64(1), object(8)
memory usage: 8.9+ MB

In [12]:
#check for null values
pd.isnull(df).sum()

movie               0
genre               0
runtime         20886
certificate    106041
rating          15510
stars            5215
description         0
votes           15498
director        41280
dtype: int64

In [13]:
# Clean runtime
df['runtime'] = df['runtime'].astype(str).str.extract('(\d+)').astype(float)

In [14]:
df.head(20)

,movie,genre,runtime,certificate,rating,stars,description,votes,director
0,The Witcher,"Action, Adventure, Drama",60.0,A,8.1,"['Henry Cavill, ', 'Freya Allan, ', 'Anya Chal...","Geralt of Rivia, a solitary monster hunter, st...","5,39,085",NaN
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163.0,UA,8.0,"['Tom Cruise, ', 'Hayley Atwell, ', 'Ving Rham...",Ethan Hunt and his IMF team must track down a ...,"1,06,759",['Christopher McQuarrie']
2,Sound of Freedom,"Action, Biography, Drama",131.0,PG-13,7.9,"['Jim Caviezel, ', 'Mira Sorvino, ', 'Bill Cam...",The incredible true story of a former governme...,"41,808",['Alejandro Monteverde']
3,Secret Invasion,"Action, Adventure, Drama",47.0,UA 16+,6.2,"['Samuel L. Jackson, ', 'Emilia Clarke, ', 'Do...",Fury and Talos try to stop the Skrulls who hav...,"40,536",NaN
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,NaN,7.5,"['Zoe Saldana, ', 'Laysla De Oliveira, ', 'Dav...",Joe attempts to balance her personal and profe...,"3,203",NaN
5,They Cloned Tyrone,"Action, Comedy, Mystery",122.0,R,6.7,"['John Boyega, ', 'Jamie Foxx, ', 'Teyonah Par...",A series of eerie events thrusts an unlikely t...,"14,271",['Juel Taylor']
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52.0,Not Rated,8.3,"['Anson Mount, ', 'Ethan Peck, ', 'Christina C...","A prequel to Star Trek: The Original Series, t...","45,723",NaN
7,One Piece,"Action, Adventure, Comedy",NaN,NaN,NaN,"['IÃ±aki Godoy, ', 'Mackenyu, ', 'Emily Rudd, '...","In a seafaring world, a young pirate captain s...",NaN,NaN
8,Twisted Metal,"Action, Adventure, Comedy",30.0,NaN,7.5,"['Anthony Mackie, ', 'Tahj Vaughans, ', 'Steph...",Follows a motor-mouthed outsider offered a cha...,"4,334",NaN
9,The Flash,"Action, Adventure, Fantasy",144.0,UA,6.9,"['Ezra Miller, ', 'Michael Keaton, ', 'Sasha C...",Barry Allen uses his super speed to change the...,"1,26,445",['Andy Muschietti']
10,Jack Ryan,"Action, Drama, Thriller",60.0,16+,8.0,"['John Krasinski, ', 'Wendell Pierce, ', 'Mich...","Up-and-coming CIA analyst, Jack Ryan, is thrus...","1,60,501",NaN
11,Transformers: Rise of the Beasts,"Action, Adventure, Sci-Fi",127.0,UA,6.1,"['Anthony Ramos, ', 'Dominique Fishback, ', 'L...","During the '90s, a new faction of Transformers...","62,180",['Steven Caple Jr.']
12,Game of Thrones,"Action, Adventure, Drama",57.0,A,9.2,"['Emilia Clarke, ', 'Peter Dinklage, ', 'Kit H...",Nine noble families fight for control over the...,"21,86,960",NaN
13,Indiana Jones and the Dial of Destiny,"Action, Adventure",154.0,UA,6.8,"['Harrison Ford, ', 'Phoebe Waller-Bridge, ', ...",Archaeologist Indiana Jones races against time...,"87,700",['James Mangold']
14,Invincible,"Animation, Action, Adventure",50.0,18,8.7,"['Steven Yeun, ', 'J.K. Simmons, ', 'Sandra Oh...",An adult animated series based on the Skybound...,"1,59,339",NaN
15,The Boys,"Action, Comedy, Crime",60.0,18+,8.7,"['Karl Urban, ', 'Jack Quaid, ', 'Antony Starr...",A group of vigilantes set out to take down cor...,"5,70,614",NaN
16,The Out-Laws,"Action, Comedy, Crime",95.0,A,5.4,"['Adam Devine, ', 'Pierce Brosnan, ', 'Ellen B...",A straight-laced bank manager about to marry t...,"24,122",['Tyler Spindel']
17,Justified,"Action, Crime, Drama",44.0,NaN,8.6,"['Timothy Olyphant, ', 'Nick Searcy, ', 'Joell...","Enforcing his own brand of justice, U.S. Marsh...","1,09,050",NaN
18,Guardians of the Galaxy Vol. 3,"Action, Adventure, Comedy",150.0,UA,8.1,"['Chris Pratt, ', 'Chukwudi Iwuji, ', 'Bradley...","Still reeling from the loss of Gamora, Peter Q...","2,37,866",['James Gunn']
19,Spider-Man: Across the Spider-Verse,"Animation, Action, Adventure",140.0,U,8.9,"['Shameik Moore, ', 'Hailee Steinfeld, ', 'Bri...","Miles Morales catapults across the Multiverse,...","1,96,674",NaN

In [15]:
# Clean votes
df['votes'] = df['votes'].astype(str).str.replace(',', '', regex=True)
df['votes'] = pd.to_numeric(df['votes'], errors='coerce')

In [16]:
df.head(10)

,movie,genre,runtime,certificate,rating,stars,description,votes,director
0,The Witcher,"Action, Adventure, Drama",60.0,A,8.1,"['Henry Cavill, ', 'Freya Allan, ', 'Anya Chal...","Geralt of Rivia, a solitary monster hunter, st...",539085.0,NaN
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163.0,UA,8.0,"['Tom Cruise, ', 'Hayley Atwell, ', 'Ving Rham...",Ethan Hunt and his IMF team must track down a ...,106759.0,['Christopher McQuarrie']
2,Sound of Freedom,"Action, Biography, Drama",131.0,PG-13,7.9,"['Jim Caviezel, ', 'Mira Sorvino, ', 'Bill Cam...",The incredible true story of a former governme...,41808.0,['Alejandro Monteverde']
3,Secret Invasion,"Action, Adventure, Drama",47.0,UA 16+,6.2,"['Samuel L. Jackson, ', 'Emilia Clarke, ', 'Do...",Fury and Talos try to stop the Skrulls who hav...,40536.0,NaN
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,NaN,7.5,"['Zoe Saldana, ', 'Laysla De Oliveira, ', 'Dav...",Joe attempts to balance her personal and profe...,3203.0,NaN
5,They Cloned Tyrone,"Action, Comedy, Mystery",122.0,R,6.7,"['John Boyega, ', 'Jamie Foxx, ', 'Teyonah Par...",A series of eerie events thrusts an unlikely t...,14271.0,['Juel Taylor']
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52.0,Not Rated,8.3,"['Anson Mount, ', 'Ethan Peck, ', 'Christina C...","A prequel to Star Trek: The Original Series, t...",45723.0,NaN
7,One Piece,"Action, Adventure, Comedy",NaN,NaN,NaN,"['IÃ±aki Godoy, ', 'Mackenyu, ', 'Emily Rudd, '...","In a seafaring world, a young pirate captain s...",NaN,NaN
8,Twisted Metal,"Action, Adventure, Comedy",30.0,NaN,7.5,"['Anthony Mackie, ', 'Tahj Vaughans, ', 'Steph...",Follows a motor-mouthed outsider offered a cha...,4334.0,NaN
9,The Flash,"Action, Adventure, Fantasy",144.0,UA,6.9,"['Ezra Miller, ', 'Michael Keaton, ', 'Sasha C...",Barry Allen uses his super speed to change the...,126445.0,['Andy Muschietti']

In [17]:
# Clean director and stars
df['director'] = df['director'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) and x.startswith('[') else [])
df['stars'] = df['stars'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) and x.startswith('[') else [])

In [18]:
df.head(10)

,movie,genre,runtime,certificate,rating,stars,description,votes,director
0,The Witcher,"Action, Adventure, Drama",60.0,A,8.1,"[Henry Cavill, , Freya Allan, , Anya Chalotra,...","Geralt of Rivia, a solitary monster hunter, st...",539085.0,[]
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163.0,UA,8.0,"[Tom Cruise, , Hayley Atwell, , Ving Rhames, ,...",Ethan Hunt and his IMF team must track down a ...,106759.0,[Christopher McQuarrie]
2,Sound of Freedom,"Action, Biography, Drama",131.0,PG-13,7.9,"[Jim Caviezel, , Mira Sorvino, , Bill Camp, , ...",The incredible true story of a former governme...,41808.0,[Alejandro Monteverde]
3,Secret Invasion,"Action, Adventure, Drama",47.0,UA 16+,6.2,"[Samuel L. Jackson, , Emilia Clarke, , Don Che...",Fury and Talos try to stop the Skrulls who hav...,40536.0,[]
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,NaN,7.5,"[Zoe Saldana, , Laysla De Oliveira, , Dave Ann...",Joe attempts to balance her personal and profe...,3203.0,[]
5,They Cloned Tyrone,"Action, Comedy, Mystery",122.0,R,6.7,"[John Boyega, , Jamie Foxx, , Teyonah Parris, ...",A series of eerie events thrusts an unlikely t...,14271.0,[Juel Taylor]
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52.0,Not Rated,8.3,"[Anson Mount, , Ethan Peck, , Christina Chong,...","A prequel to Star Trek: The Original Series, t...",45723.0,[]
7,One Piece,"Action, Adventure, Comedy",NaN,NaN,NaN,"[IÃ±aki Godoy, , Mackenyu, , Emily Rudd, , Jaco...","In a seafaring world, a young pirate captain s...",NaN,[]
8,Twisted Metal,"Action, Adventure, Comedy",30.0,NaN,7.5,"[Anthony Mackie, , Tahj Vaughans, , Stephanie ...",Follows a motor-mouthed outsider offered a cha...,4334.0,[]
9,The Flash,"Action, Adventure, Fantasy",144.0,UA,6.9,"[Ezra Miller, , Michael Keaton, , Sasha Calle,...",Barry Allen uses his super speed to change the...,126445.0,[Andy Muschietti]

In [19]:
# Fill or drop missing
df['certificate'].fillna("Not Rated", inplace=True)
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df.dropna(subset=['rating'], inplace=True)

In [20]:
df.head(10)

,movie,genre,runtime,certificate,rating,stars,description,votes,director
0,The Witcher,"Action, Adventure, Drama",60.0,A,8.1,"[Henry Cavill, , Freya Allan, , Anya Chalotra,...","Geralt of Rivia, a solitary monster hunter, st...",539085.0,[]
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163.0,UA,8.0,"[Tom Cruise, , Hayley Atwell, , Ving Rhames, ,...",Ethan Hunt and his IMF team must track down a ...,106759.0,[Christopher McQuarrie]
2,Sound of Freedom,"Action, Biography, Drama",131.0,PG-13,7.9,"[Jim Caviezel, , Mira Sorvino, , Bill Camp, , ...",The incredible true story of a former governme...,41808.0,[Alejandro Monteverde]
3,Secret Invasion,"Action, Adventure, Drama",47.0,UA 16+,6.2,"[Samuel L. Jackson, , Emilia Clarke, , Don Che...",Fury and Talos try to stop the Skrulls who hav...,40536.0,[]
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,Not Rated,7.5,"[Zoe Saldana, , Laysla De Oliveira, , Dave Ann...",Joe attempts to balance her personal and profe...,3203.0,[]
5,They Cloned Tyrone,"Action, Comedy, Mystery",122.0,R,6.7,"[John Boyega, , Jamie Foxx, , Teyonah Parris, ...",A series of eerie events thrusts an unlikely t...,14271.0,[Juel Taylor]
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52.0,Not Rated,8.3,"[Anson Mount, , Ethan Peck, , Christina Chong,...","A prequel to Star Trek: The Original Series, t...",45723.0,[]
8,Twisted Metal,"Action, Adventure, Comedy",30.0,Not Rated,7.5,"[Anthony Mackie, , Tahj Vaughans, , Stephanie ...",Follows a motor-mouthed outsider offered a cha...,4334.0,[]
9,The Flash,"Action, Adventure, Fantasy",144.0,UA,6.9,"[Ezra Miller, , Michael Keaton, , Sasha Calle,...",Barry Allen uses his super speed to change the...,126445.0,[Andy Muschietti]
10,Jack Ryan,"Action, Drama, Thriller",60.0,16+,8.0,"[John Krasinski, , Wendell Pierce, , Michael K...","Up-and-coming CIA analyst, Jack Ryan, is thrus...",160501.0,[]

In [21]:
# Add a helper column for primary director/star
df['primary_director'] = df['director'].apply(lambda x: x[0] if x else np.nan)
df['primary_star'] = df['stars'].apply(lambda x: x[0].strip() if x else np.nan)

In [22]:
df.head(10)

,movie,genre,runtime,certificate,rating,stars,description,votes,director,primary_director,primary_star
0,The Witcher,"Action, Adventure, Drama",60.0,A,8.1,"[Henry Cavill, , Freya Allan, , Anya Chalotra,...","Geralt of Rivia, a solitary monster hunter, st...",539085.0,[],NaN,"Henry Cavill,"
1,Mission: Impossible - Dead Reckoning Part One,"Action, Adventure, Thriller",163.0,UA,8.0,"[Tom Cruise, , Hayley Atwell, , Ving Rhames, ,...",Ethan Hunt and his IMF team must track down a ...,106759.0,[Christopher McQuarrie],Christopher McQuarrie,"Tom Cruise,"
2,Sound of Freedom,"Action, Biography, Drama",131.0,PG-13,7.9,"[Jim Caviezel, , Mira Sorvino, , Bill Camp, , ...",The incredible true story of a former governme...,41808.0,[Alejandro Monteverde],Alejandro Monteverde,"Jim Caviezel,"
3,Secret Invasion,"Action, Adventure, Drama",47.0,UA 16+,6.2,"[Samuel L. Jackson, , Emilia Clarke, , Don Che...",Fury and Talos try to stop the Skrulls who hav...,40536.0,[],NaN,"Samuel L. Jackson,"
4,Special Ops: Lioness,"Action, Drama, Thriller",NaN,Not Rated,7.5,"[Zoe Saldana, , Laysla De Oliveira, , Dave Ann...",Joe attempts to balance her personal and profe...,3203.0,[],NaN,"Zoe Saldana,"
5,They Cloned Tyrone,"Action, Comedy, Mystery",122.0,R,6.7,"[John Boyega, , Jamie Foxx, , Teyonah Parris, ...",A series of eerie events thrusts an unlikely t...,14271.0,[Juel Taylor],Juel Taylor,"John Boyega,"
6,Star Trek: Strange New Worlds,"Action, Adventure, Sci-Fi",52.0,Not Rated,8.3,"[Anson Mount, , Ethan Peck, , Christina Chong,...","A prequel to Star Trek: The Original Series, t...",45723.0,[],NaN,"Anson Mount,"
8,Twisted Metal,"Action, Adventure, Comedy",30.0,Not Rated,7.5,"[Anthony Mackie, , Tahj Vaughans, , Stephanie ...",Follows a motor-mouthed outsider offered a cha...,4334.0,[],NaN,"Anthony Mackie,"
9,The Flash,"Action, Adventure, Fantasy",144.0,UA,6.9,"[Ezra Miller, , Michael Keaton, , Sasha Calle,...",Barry Allen uses his super speed to change the...,126445.0,[Andy Muschietti],Andy Muschietti,"Ezra Miller,"
10,Jack Ryan,"Action, Drama, Thriller",60.0,16+,8.0,"[John Krasinski, , Wendell Pierce, , Michael K...","Up-and-coming CIA analyst, Jack Ryan, is thrus...",160501.0,[],NaN,"John Krasinski,"

In [23]:
df.shape

(114381, 11)